# Generated by Django 4.1.3 on 2022-12-01 02:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleOwnerInformation',
            fields=[
                ('first_name', models.CharField(max_length=64, verbose_name='first name')),
                ('last_name', models.CharField(max_length=64, verbose_name='middle name')),
                ('email', models.EmailField(max_length=320, verbose_name='email address')),
                ('volunteer_type', models.CharField(choices=[('Faculty', ''), ('Student', '')], max_length=7, verbose_name='volunteer type')),
                ('registration_number', models.CharField(max_length=15, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('[MITU].*', message='Invalid Registration Number')], verbose_name='institute registration number')),
                ('college_name', models.CharField(choices=[('MIT-SOE', 'MIT School of Engineering'), ('MIT-ID', 'MIT Institue of Design'), ('MANET', 'Maharashtra Academy of Naval Education & Training'), ('MIT-SBSR', 'MIT School of Bio-Engineering Sciences and Research')], max_length=255, verbose_name='college_name')),
            ],
            options={
                'db_table': 'VehicleOwnerInformation',
            },
        ),
        migrations.CreateModel(
            name='VehicleInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('MC', 'Scooters, Bikes'), ('LMV', 'Cars'), ('TRANS', 'Transport Vehicles')], max_length=6)),
                ('vehicle_make', models.CharField(max_length=255)),
                ('license_plate', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('(([A-Za-z]){2,3}(|-)(?:[0-9]){1,2}(|-)(?:[A-Za-z]){2}(|-)([0-9]){1,4})|(([A-Za-z]){2,3}(|-)([0-9]){1,4})', message='Invalid License Plate')])),
                ('registration_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.vehicleownerinformation')),
            ],
            options={
                'db_table': 'VehicleInformation',
            },
        ),
    ]
